
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:123456@tcp(localhost:3306)/xiuadmin?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
        tables: "sys_notice_user,sys_config,sys_gen_table,sys_notice,sys_oss,sys_social"
        descriptionTag:  true # 数据表字段注释
        noModelComment:  true
        jsonCase: "CamelLower" # 生成json字段时，字段名使用驼峰命名
        gJsonSupport: true
        group: "default"                      # 分组 使用代码生成功能时必须填
        tablesEx: "sys_addons_install"        # 指定当前数据库中需要排除代码生成的数据表。

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app