// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package monitor

import (
	"xiuadmin/api/monitor"
)

type ControllerV1 struct{}

func NewV1() monitor.IMonitorV1 {
	return &ControllerV1{}
}
