// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiujieadmin/internal/dao/internal"
)

// internalSysOperLogDao is an internal type for wrapping the internal DAO implementation.
type internalSysOperLogDao = *internal.SysOperLogDao

// sysOperLogDao is the data access object for the table sys_oper_log.
// You can define custom methods on it to extend its functionality as needed.
type sysOperLogDao struct {
	internalSysOperLogDao
}

var (
	// SysOperLog is a globally accessible object for table sys_oper_log operations.
	SysOperLog = sysOperLogDao{
		internal.NewSysOperLogDao(),
	}
)

// Add your custom methods and functionality below.
