// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysClientDao is an internal type for wrapping the internal DAO implementation.
type internalSysClientDao = *internal.SysClientDao

// sysClientDao is the data access object for the table sys_client.
// You can define custom methods on it to extend its functionality as needed.
type sysClientDao struct {
	internalSysClientDao
}

var (
	// SysClient is a globally accessible object for table sys_client operations.
	SysClient = sysClientDao{
		internal.NewSysClientDao(),
	}
)

// Add your custom methods and functionality below.
