// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysUserOnlineDao is an internal type for wrapping the internal DAO implementation.
type internalSysUserOnlineDao = *internal.SysUserOnlineDao

// sysUserOnlineDao is the data access object for the table sys_user_online.
// You can define custom methods on it to extend its functionality as needed.
type sysUserOnlineDao struct {
	internalSysUserOnlineDao
}

var (
	// SysUserOnline is a globally accessible object for table sys_user_online operations.
	SysUserOnline = sysUserOnlineDao{
		internal.NewSysUserOnlineDao(),
	}
)

// Add your custom methods and functionality below.
