// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysPostDao is an internal type for wrapping the internal DAO implementation.
type internalSysPostDao = *internal.SysPostDao

// sysPostDao is the data access object for the table sys_post.
// You can define custom methods on it to extend its functionality as needed.
type sysPostDao struct {
	internalSysPostDao
}

var (
	// SysPost is a globally accessible object for table sys_post operations.
	SysPost = sysPostDao{
		internal.NewSysPostDao(),
	}
)

// Add your custom methods and functionality below.
