// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiujieadmin/internal/dao/internal"
)

// internalSysLogininforDao is an internal type for wrapping the internal DAO implementation.
type internalSysLogininforDao = *internal.SysLogininforDao

// sysLogininforDao is the data access object for the table sys_logininfor.
// You can define custom methods on it to extend its functionality as needed.
type sysLogininforDao struct {
	internalSysLogininforDao
}

var (
	// SysLogininfor is a globally accessible object for table sys_logininfor operations.
	SysLogininfor = sysLogininforDao{
		internal.NewSysLogininforDao(),
	}
)

// Add your custom methods and functionality below.
