// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiuadmin/internal/dao/internal"
)

// sysJobDao is the data access object for the table sys_job.
// You can define custom methods on it to extend its functionality as needed.
type sysJobDao struct {
	*internal.SysJobDao
}

var (
	// SysJob is a globally accessible object for table sys_job operations.
	SysJob = sysJobDao{internal.NewSysJobDao()}
)

// Add your custom methods and functionality below.
