// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiuadmin/internal/dao/internal"
)

// internalSysDeptDao is an internal type for wrapping the internal DAO implementation.
type internalSysDeptDao = *internal.SysDeptDao

// sysDeptDao is the data access object for the table sys_dept.
// You can define custom methods on it to extend its functionality as needed.
type sysDeptDao struct {
	internalSysDeptDao
}

var (
	// SysDept is a globally accessible object for table sys_dept operations.
	SysDept = sysDeptDao{
		internal.NewSysDeptDao(),
	}
)

// Add your custom methods and functionality below.
