// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiuadmin/internal/dao/internal"
)

// sysNoticeUserDao is the data access object for the table sys_notice_user.
// You can define custom methods on it to extend its functionality as needed.
type sysNoticeUserDao struct {
	*internal.SysNoticeUserDao
}

var (
	// SysNoticeUser is a globally accessible object for table sys_notice_user operations.
	SysNoticeUser = sysNoticeUserDao{internal.NewSysNoticeUserDao()}
)

// Add your custom methods and functionality below.
