// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysOssDao is an internal type for wrapping the internal DAO implementation.
type internalSysOssDao = *internal.SysOssDao

// sysOssDao is the data access object for the table sys_oss.
// You can define custom methods on it to extend its functionality as needed.
type sysOssDao struct {
	internalSysOssDao
}

var (
	// SysOss is a globally accessible object for table sys_oss operations.
	SysOss = sysOssDao{
		internal.NewSysOssDao(),
	}
)

// Add your custom methods and functionality below.
