// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiuadmin/internal/dao/internal"
)

// internalSysGenTableDao is an internal type for wrapping the internal DAO implementation.
type internalSysGenTableDao = *internal.SysGenTableDao

// sysGenTableDao is the data access object for the table sys_gen_table.
// You can define custom methods on it to extend its functionality as needed.
type sysGenTableDao struct {
	internalSysGenTableDao
}

var (
	// SysGenTable is a globally accessible object for table sys_gen_table operations.
	SysGenTable = sysGenTableDao{
		internal.NewSysGenTableDao(),
	}
)

// Add your custom methods and functionality below.
