// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysUserDao is an internal type for wrapping the internal DAO implementation.
type internalSysUserDao = *internal.SysUserDao

// sysUserDao is the data access object for the table sys_user.
// You can define custom methods on it to extend its functionality as needed.
type sysUserDao struct {
	internalSysUserDao
}

var (
	// SysUser is a globally accessible object for table sys_user operations.
	SysUser = sysUserDao{
		internal.NewSysUserDao(),
	}
)

// Add your custom methods and functionality below.
