// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiuadmin/internal/dao/internal"
)

// internalSysOssConfigDao is an internal type for wrapping the internal DAO implementation.
type internalSysOssConfigDao = *internal.SysOssConfigDao

// sysOssConfigDao is the data access object for the table sys_oss_config.
// You can define custom methods on it to extend its functionality as needed.
type sysOssConfigDao struct {
	internalSysOssConfigDao
}

var (
	// SysOssConfig is a globally accessible object for table sys_oss_config operations.
	SysOssConfig = sysOssConfigDao{
		internal.NewSysOssConfigDao(),
	}
)

// Add your custom methods and functionality below.
