// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiuadmin/internal/dao/internal"
)

// internalSysSocialDao is an internal type for wrapping the internal DAO implementation.
type internalSysSocialDao = *internal.SysSocialDao

// sysSocialDao is the data access object for the table sys_social.
// You can define custom methods on it to extend its functionality as needed.
type sysSocialDao struct {
	internalSysSocialDao
}

var (
	// SysSocial is a globally accessible object for table sys_social operations.
	SysSocial = sysSocialDao{
		internal.NewSysSocialDao(),
	}
)

// Add your custom methods and functionality below.
