// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiuadmin/internal/dao/internal"
)

// internalSysUserRoleDao is an internal type for wrapping the internal DAO implementation.
type internalSysUserRoleDao = *internal.SysUserRoleDao

// sysUserRoleDao is the data access object for the table sys_user_role.
// You can define custom methods on it to extend its functionality as needed.
type sysUserRoleDao struct {
	internalSysUserRoleDao
}

var (
	// SysUserRole is a globally accessible object for table sys_user_role operations.
	SysUserRole = sysUserRoleDao{
		internal.NewSysUserRoleDao(),
	}
)

// Add your custom methods and functionality below.
