// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiuadmin/internal/dao/internal"
)

// internalSysNoticeDao is an internal type for wrapping the internal DAO implementation.
type internalSysNoticeDao = *internal.SysNoticeDao

// sysNoticeDao is the data access object for the table sys_notice.
// You can define custom methods on it to extend its functionality as needed.
type sysNoticeDao struct {
	internalSysNoticeDao
}

var (
	// SysNotice is a globally accessible object for table sys_notice operations.
	SysNotice = sysNoticeDao{
		internal.NewSysNoticeDao(),
	}
)

// Add your custom methods and functionality below.
