// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiujieadmin/internal/dao/internal"
)

// internalSysUserPostDao is an internal type for wrapping the internal DAO implementation.
type internalSysUserPostDao = *internal.SysUserPostDao

// sysUserPostDao is the data access object for the table sys_user_post.
// You can define custom methods on it to extend its functionality as needed.
type sysUserPostDao struct {
	internalSysUserPostDao
}

var (
	// SysUserPost is a globally accessible object for table sys_user_post operations.
	SysUserPost = sysUserPostDao{
		internal.NewSysUserPostDao(),
	}
)

// Add your custom methods and functionality below.
