// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiuadmin/internal/dao/internal"
)

// internalSysTenantPackageDao is an internal type for wrapping the internal DAO implementation.
type internalSysTenantPackageDao = *internal.SysTenantPackageDao

// sysTenantPackageDao is the data access object for the table sys_tenant_package.
// You can define custom methods on it to extend its functionality as needed.
type sysTenantPackageDao struct {
	internalSysTenantPackageDao
}

var (
	// SysTenantPackage is a globally accessible object for table sys_tenant_package operations.
	SysTenantPackage = sysTenantPackageDao{
		internal.NewSysTenantPackageDao(),
	}
)

// Add your custom methods and functionality below.
