// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiujieadmin/internal/dao/internal"
)

// internalSysRoleDeptDao is an internal type for wrapping the internal DAO implementation.
type internalSysRoleDeptDao = *internal.SysRoleDeptDao

// sysRoleDeptDao is the data access object for the table sys_role_dept.
// You can define custom methods on it to extend its functionality as needed.
type sysRoleDeptDao struct {
	internalSysRoleDeptDao
}

var (
	// SysRoleDept is a globally accessible object for table sys_role_dept operations.
	SysRoleDept = sysRoleDeptDao{
		internal.NewSysRoleDeptDao(),
	}
)

// Add your custom methods and functionality below.
