// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysDictDataDao is an internal type for wrapping the internal DAO implementation.
type internalSysDictDataDao = *internal.SysDictDataDao

// sysDictDataDao is the data access object for the table sys_dict_data.
// You can define custom methods on it to extend its functionality as needed.
type sysDictDataDao struct {
	internalSysDictDataDao
}

var (
	// SysDictData is a globally accessible object for table sys_dict_data operations.
	SysDictData = sysDictDataDao{
		internal.NewSysDictDataDao(),
	}
)

// Add your custom methods and functionality below.
