// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiujieadmin/internal/dao/internal"
)

// testDemoDao is the data access object for the table test_demo.
// You can define custom methods on it to extend its functionality as needed.
type testDemoDao struct {
	*internal.TestDemoDao
}

var (
	// TestDemo is a globally accessible object for table test_demo operations.
	TestDemo = testDemoDao{internal.NewTestDemoDao()}
)

// Add your custom methods and functionality below.
