// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xiuadmin/internal/dao/internal"
)

// testTreeDao is the data access object for the table test_tree.
// You can define custom methods on it to extend its functionality as needed.
type testTreeDao struct {
	*internal.TestTreeDao
}

var (
	// TestTree is a globally accessible object for table test_tree operations.
	TestTree = testTreeDao{internal.NewTestTreeDao()}
)

// Add your custom methods and functionality below.
