// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package gen_codes

import (
	"xiuadmin/api/gen_codes"
)

type ControllerV1 struct{}

func NewV1() gen_codes.IGenCodesV1 {
	return &ControllerV1{}
}
