// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package info

import (
	"xiuadmin/api/info"
)

type ControllerV1 struct{}

func NewV1() info.IInfoV1 {
	return &ControllerV1{}
}
